runtime: python39
instance_class: F2

entrypoint: gunicorn -b :$PORT app:app

env_variables:
  AUTH0_DOMAIN:      ""
  API_AUDIENCE:      ""
  AUTH0_CLIENT_ID:   ""
  AUTH0_CLIENT_SECRET: ""
  BUCKET_NAME:     ""
  AUTH0_REALM:     ""
